= Creando una aplicación simple usando enrutamiento en Vaadin

_Traducido del https://vaadin.com/learn/tutorials/vaadin-router[original en Inglés]._

Nosotros no vamos a asumir ninguna herramienta, la aplicación incluye todo lo necesario para correr y ejecutarse en cualquier navegador

== 1. Configuración del proyecto

Primero vamos a crear el `*index.html*`, vamos a adicionar unas etiquetas e incluir unos scripts

.`*index.html*`
[source,html]
----
<base href="/">

<!-- Include the Vaadin.Router library.
     Browsers automatically pick the best of the two options below. -->
<script nomodule src="https://unpkg.com/@vaadin/router/dist/vaadin-router.umd.js"></script>
<script type="module" src="https://unpkg.com/@vaadin/router"></script>

<nav>
  <!-- By default Vaadin.Router intercepts all anchor clicks and
       uses them for in-app navigation -->
  <a href="/">Home</a>
  <a href="/about">About</a>
</nav>

<main id="outlet">
  <!-- Here Vaadin.Router inserts the current page content -->
</main>

<script src="app.js"></script>
---- 

.`*app.js*`
[source,javascript]
----
const {Router} = window.Vaadin;

// setup a Router instance
const outlet = document.getElementById('outlet');
const router = new Router(outlet);
---- 

Ahora podemos llamar la instancia del `*Router*` y lo usaremos para configurar las rutas de nuestra aplicación. 

== 2. Configuración básica de las rutas

Ahora es tiempo de configurar nuestra primera ruta. La configuración de ruta asigna la ruta a un https://www.webcomponents.org/introduction[Web Component]. `*Vaadin.Router* recorre las rutas configuradas hasta que encuentra la primera coincidencia, a partir de eso crea una instancia del componente atado a la ruta y la inserta en la salida del enrutador (reemplaza cualquier contenido existente)

El enrutador no obliga a seguir un formato específico para definir los componentes, puede escribir elementos personalizados (Custom elements) en Vanilla, o user cualquier librería que ayude a crearlos. Ejemplo: Polymer, Angular, Vue, SkateJS, Aurelia, etc.

Vamos a crear un componente web de vanilla para la vista de inicio. Tenga en cuenta el guión en el nombre de la etiqueta, es requerido por el estandar.

[source,javascript]
----
// Extend an HTMLElement or another custom element
class HomeView extends HTMLElement {
	// This is called when our element is attached to the DOM
	connectedCallback() {
		this.innerHTML = `<h1>Welcome home!</h1>`;
	}
}
// Tell the browser to associate the '<home-view>' tag with HomeView class
customElements.define('home-view', HomeView);
----

y luego le diremos al visualizador que el componente `*<home-view>*` será la ruta raíz usando el método `*setRoutes*`:

[source,javascript]
----
router.setRoutes([
  {path: '/', component: 'home-view'},
]);
----

¡Eso es! Ahora, podemos iniciar un servidor de desarrollo y abrir la página en el navegador. Tenga en cuenta que los componentes web funcionan de forma nativa en las últimas versiones de Chrome y Safari.

Para otros navegadores, deberá instalar el polyfill y agregar el script a la página. El polyfill utiliza la detección de características y solo carga los scripts necesarios para que las características que faltan funcionen.

== 3. Enrutamiento de errores

== 4. Parámetros en las rutas

== 5. Redireccionamiento incondicional

== 6. Emparejamiento ambiguo




